# Generated by Django 5.2.11 on 2026-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_employee_vehicle_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_service',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
