# Generated by Django 5.2.11 on 2026-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteservice_delete_react'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteservice',
            name='image_url',
        ),
        migrations.AddField(
            model_name='siteservice',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
