# Generated by Django 5.2.12 on 2026-03-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_siteservice_image_url_siteservice_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('vehicle', 'scheduled_at'), name='unique_vehicle_scheduled_at'),
        ),
    ]
