# Generated by Django 5.2.12 on 2026-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_siteservice_image_url_siteservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hours', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'business_information',
            },
        ),
    ]
