# Generated by Django 5.2.12 on 2026-03-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_unique_vehicle_scheduled_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_vehicle_scheduled_at',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('scheduled_at',), name='unique_scheduled_at'),
        ),
    ]
