# Generated by Django 5.2.11 on 2026-03-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessinformation'),
        ('core', '0006_remove_appointment_unique_vehicle_scheduled_at_and_more'),
    ]

    operations = [
    ]
