# Generated by Django 5.2.12 on 2026-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messsage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
                ('response', models.BooleanField(default=False)),
                ('current_customer', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
