# Generated by Django 5.2.12 on 2026-04-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='services',
        ),
    ]
