# Generated by Django 5.2.11 on 2026-04-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messsage'),
        ('core', '0010_remove_invoice_services'),
    ]

    operations = [
    ]
