# Generated by Django 5.2.11 on 2026-04-21 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_0010_messsage_0010_remove_invoice_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messsage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='messsage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messsage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
