# Generated by Django 5.2.11 on 2026-04-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_messsage_options_messsage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='core.siteservice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.siteservice'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
