# Generated by Django 5.2.11 on 2026-04-22 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_appointment_services_remove_invoice_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLineItem',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.appointment')),
            ],
            options={
                'db_table': 'appointment_line_item',
                'ordering': ['line_id'],
            },
        ),
    ]
