# Generated by Django 5.2.12 on 2026-05-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appointmentlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('digital', 'Digital')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
