# Generated by Django 5.2.12 on 2026-05-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_paymentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64, unique=True)),
                ('access_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
